version: 2

sources:
  - name: public
    tables:
      - name: city_day_aqi
        meta:
          dagster:
            asset_key: ["city_day_source"] # This metadata specifies the corresponding Dagster asset for this dbt source.
