[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "air_quality_source_pipeline.definitions"
code_location_name = "air_quality_source_pipeline"